package org.w3c.dom.events
{
	import java.lang.Throwable;
	import org.w3c.dom.DOMException;
	
	/**
	* 	Exception generated by the DOM Events module.
	*/
	public class EventException extends DOMException
	{
		/**
		* 	If the Event.type was not specified by initializing
		* 	the event before the method was called. Specification
		* 	of the Event.type as null or an empty string must also
		* 	trigger this exception.
		*/
		public static const UNSPECIFIED_EVENT_TYPE_ERR:int = 0;
		
		/**
		* 	If the Event object is already dispatched in the tree.
		*/
		public static const DISPATCH_REQUEST_ERR:int = 1;
		
		/**
		* 	Creates a <code>EventException</code> instance.
		* 
		* 	@param message The detail message.
		* 	@param couse The cause, a null value is permitted,
		* 	and indicates that the cause is nonexistent or unknown.
		* 	@param id An identifier for the exception.
		* 	@param replacements Values to replace within
		* 	the detail message.
		*/
		public function EventException(
			message:String = null,
			cause:Throwable = null,
			id:int = 0,
			replacements:Array = null )
		{
			super( message, cause, id, replacements );
		}
	}
}